[server]

# If false, will attempt to open a browser window on start.
headless = true

# Enables support for Cross-Origin Resource Sharing (CORS) protection, for
# added security.
enableCORS = true


[browser]

# Whether to send usage statistics to Streamlit.
gatherUsageStats = false

