[dataframe]

# A file path relative to the runner script pointing to the data source file.
# Required for widgets to work, as all computations are performed on demand.
path = "./data/dataframe.csv"


[assets]

# A file path relative to the runner script pointing to the static images directory.
path = "./static"

